package kr.famos.base.mapper;

import kr.famos.base.domain.LastTable;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;

/**
 * Created by yhkim on 2017-01-31.
 */
@Mapper
public interface LastTableMapper {
    @Select("SELECT * FROM LAST_TABLE")
    public List<LastTable> readAllLastTable();

    @Insert("INSERT\n" +
            "INTO\n" +
            "      LAST_TABLE\n" +
            "      (\n" +
            "            SYS_DATE,\n" +
            "            TESTER,\n" +
            "            PARTNUMBER,\n" +
            "            PROCESS,\n" +
            "            MAIN_PGM,\n" +
            "            PGMCNT,\n" +
            "            SUB_PGM,\n" +
            "            GLOBAL,\n" +
            "            SBL_YIELD,\n" +
            "            SUB_BIN,\n" +
            "            SUBBIN,\n" +
            "            NGBIN,\n" +
            "            PKG_SIGMOD,\n" +
            "            PKG_PARA,\n" +
            "            PKG_DIGIT,\n" +
            "            PKG_SIGNO,\n" +
            "            PKG_MEASNO,\n" +
            "            FLOW,\n" +
            "            HALT,\n" +
            "            COMMENTS,\n" +
            "            RUN_SBL,\n" +
            "            RUN_COUNT,\n" +
            "            TEMP,\n" +
            "            TEMP_LIMIT,\n" +
            "            PKG_TYPE,\n" +
            "            PKG_SIZE,\n" +
            "            PKG_HEIGHT,\n" +
            "            PKG_PARANUM,\n" +
            "            SPECIAL_PARA,\n" +
            "            RUN_SBL_YIELD,\n" +
            "            LEADFREE,\n" +
            "            LOT_MERGE,\n" +
            "            NEW_PRODUCT,\n" +
            "            CATE6_1,\n" +
            "            CATE6_2,\n" +
            "            CATE6_3,\n" +
            "            CATE6_4,\n" +
            "            CATE6_5,\n" +
            "            CATE7_1,\n" +
            "            CATE7_2,\n" +
            "            CATE7_3,\n" +
            "            CATE7_4,\n" +
            "            CATE7_5,\n" +
            "            PRIME_PORTION,\n" +
            "            YIELD_SBL,\n" +
            "            NEW_SUB_BIN,\n" +
            "            T_LOT_SBL,\n" +
            "            RTS_SUB,\n" +
            "            RTS_NG,\n" +
            "            RTS_YIELD,\n" +
            "            RTS_FLOW,\n" +
            "            RTS_MIN_YIELD,\n" +
            "            RTS_BIN8_MIN_CNT,\n" +
            "            MASK_FLOW,\n" +
            "            MASK_COMMENTS,\n" +
            "            EXCEPT_LOT,\n" +
            "            EXCEPT_INPUT_CNT,\n" +
            "            TMS_USING,\n" +
            "            AQL_BIN,\n" +
            "            NCF_RULE,\n" +
            "            FAIL_SUM,\n" +
            "            FAIL_SUM_CMD,\n" +
            "            PGM_MONITOR_CNT,\n" +
            "            TEST_CHIP,\n" +
            "            OPIRUS_MONITOR_CNT,\n" +
            "            WAFER_SBL,\n" +
            "            WAFER_LIMIT_CNT,\n" +
            "            WAFER_LOT_FILTER,\n" +
            "            WAFER_SBL_BIN,\n" +
            "            S_BIN,\n" +
            "            SH_PROCESS,\n" +
            "            SH_LOTID_1ST,\n" +
            "            SH_LOTID_2ND,\n" +
            "            SH_PROCESS_1ST,\n" +
            "            SH_PROCESS_2ND,\n" +
            "            TEST_TIME,\n" +
            "            ITEM_COUNT,\n" +
            "            MAX_TIME,\n" +
            "            WAFER_CI_BIN,\n" +
            "            PURPOSE_TYPE_CHECK,\n" +
            "            PURPOSE_TYPE_1ST,\n" +
            "            PURPOSE_PROCESS_1ST,\n" +
            "            PURPOSE_TYPE_2ND,\n" +
            "            PURPOSE_PROCESS_2ND,\n" +
            "            WAFER_SBL_FLAG,\n" +
            "            MULTIUI_FLAG,\n" +
            "            FW_NAME_CHECK,\n" +
            "            FW1_PGM,\n" +
            "            FW_PATCH,\n" +
            "            FW_RC,\n" +
            "            FW_RELEASE_DATE,\n" +
            "            FW2_PGM,\n" +
            "            FW3_PGM,\n" +
            "            RELEASE_DATE_CHECK,\n" +
            "            FAB,\n" +
            "            GRADE\n" +
            "      )\n" +
            "      VALUES\n" +
            "      (\n" +
            "            {#operator},\n" +
            "            {#sysDate},\n" +
            "            {#tester},\n" +
            "            {#partnumber},\n" +
            "            {#process},\n" +
            "            {#mainPgm},\n" +
            "            {#pgmcnt},\n" +
            "            {#subPgm},\n" +
            "            {#global},\n" +
            "            {#sblYield},\n" +
            "            {#subBin},\n" +
            "            {#subbin},\n" +
            "            {#ngbin},\n" +
            "            {#pkgSigmod},\n" +
            "            {#pkgPara},\n" +
            "            {#pkgDigit},\n" +
            "            {#pkgSigno},\n" +
            "            {#pkgMeasno},\n" +
            "            {#flow},\n" +
            "            {#halt},\n" +
            "            {#comments},\n" +
            "            {#runSbl},\n" +
            "            {#runCount},\n" +
            "            {#temp},\n" +
            "            {#tempLimit},\n" +
            "            {#pkgType},\n" +
            "            {#pkgSize},\n" +
            "            {#pkgHeight},\n" +
            "            {#pkgParanum},\n" +
            "            {#specialPara},\n" +
            "            {#runSblYield},\n" +
            "            {#leadfree},\n" +
            "            {#lotMerge},\n" +
            "            {#newProduct},\n" +
            "            {#cate61},\n" +
            "            {#cate62},\n" +
            "            {#cate63},\n" +
            "            {#cate64},\n" +
            "            {#cate65},\n" +
            "            {#cate71},\n" +
            "            {#cate72},\n" +
            "            {#cate73},\n" +
            "            {#cate74},\n" +
            "            {#cate75},\n" +
            "            {#primePortion},\n" +
            "            {#yieldSbl},\n" +
            "            {#newSubBin},\n" +
            "            {#tLotSbl},\n" +
            "            {#rtsSub},\n" +
            "            {#rtsNg},\n" +
            "            {#rtsYield},\n" +
            "            {#rtsFlow},\n" +
            "            {#rtsMinYield},\n" +
            "            {#rtsBin8MinCnt},\n" +
            "            {#maskFlow},\n" +
            "            {#maskComments},\n" +
            "            {#exceptLot},\n" +
            "            {#exceptInputCnt},\n" +
            "            {#tmsUsing},\n" +
            "            {#aqlBin},\n" +
            "            {#ncfRule},\n" +
            "            {#failSum},\n" +
            "            {#failSumCmd},\n" +
            "            {#pgmMonitorCnt},\n" +
            "            {#testChip},\n" +
            "            {#opirusMonitorCnt},\n" +
            "            {#waferSbl},\n" +
            "            {#waferLimitCnt},\n" +
            "            {#waferLotFilter},\n" +
            "            {#waferSblBin},\n" +
            "            {#sBin},\n" +
            "            {#shProcess},\n" +
            "            {#shLotid1st},\n" +
            "            {#shLotid2nd},\n" +
            "            {#shProcess1st},\n" +
            "            {#shProcess2nd},\n" +
            "            {#testTime},\n" +
            "            {#itemCount},\n" +
            "            {#maxTime},\n" +
            "            {#waferCiBin},\n" +
            "            {#purposeTypeCheck},\n" +
            "            {#purposeType1st},\n" +
            "            {#purposeProcess1st},\n" +
            "            {#purposeType2nd},\n" +
            "            {#purposeProcess2nd},\n" +
            "            {#waferSblFlag},\n" +
            "            {#multiuiFlag},\n" +
            "            {#fwNameCheck},\n" +
            "            {#fw1Pgm},\n" +
            "            {#fwPatch},\n" +
            "            {#fwRc},\n" +
            "            {#fwReleaseDate},\n" +
            "            {#fw2Pgm},\n" +
            "            {#fw3Pgm},\n" +
            "            {#releaseDateCheck},\n" +
            "            {#fab},\n" +
            "            {#grade}\n" +
            "      )")
    public void insertLastTable(LastTable lastTable);
}
