package kr.famos.bets.yieldAnalysis.ngbin.service;

import com.google.gson.Gson;
import kr.famos.bets.yieldAnalysis.ngbin.dto.NgBinDto;
import kr.famos.bets.yieldAnalysis.ngbin.dto.NgBinResultDto;
import kr.famos.bets.yieldAnalysis.ngbin.mapper.NgBinMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Created by yhkim on 2017-03-08.
 */
@Service
public class NgBinService {
    private static final Logger logger = LoggerFactory.getLogger(NgBinService.class);

    @Autowired
    NgBinMapper ngBinMapper;

    public List<NgBinDto> retireveNgBin(NgBinDto ngBinDto) {
        List<NgBinDto> ngBinDtoList = ngBinMapper.retireveNgBin(ngBinDto);
        return ngBinDtoList;
    }

    public List<NgBinResultDto> retrieveNgBinJson(NgBinDto ngBinDto) {

        List<NgBinDto> ngBinDtoList = ngBinMapper.retireveNgBinJson(ngBinDto);

        List<NgBinResultDto> ngBinResultDtoList = new ArrayList<>();
        logger.debug("SubBinService - retrieveSubBin : " + ngBinDto.getTestCounter());

        //반환된 리스트의 각 한줄을 파싱하여 새로운 JSON 객체로 변환하여 리턴한다.
        //변환된 JSON에는 엔지빈의 번호에 따라
        for(NgBinDto list : ngBinDtoList){
            String strNgBin = list.getNgBin();
            StringTokenizer tokens = new StringTokenizer(strNgBin, ",");    //맵으로 분리
            HashMap<Integer, String> map = new HashMap<>();
            String ngBintoken;
            int mapKey = 0;
            String mapValue;

            int tokenTotal = tokens.countTokens();
            for (int i = 0; i < tokenTotal; i++) {
                if (i % 2 == 0) {
                    ngBintoken = tokens.nextToken();
                    mapKey = Integer.parseInt(ngBintoken);
                } else {
//                    mapValue = Integer.parseInt(tokens.nextToken());
                    mapValue = tokens.nextToken();
                    map.put(mapKey, mapValue);
                }
            }

            TreeMap<Integer, String> tm = new TreeMap<>(map);    //기본 오름차순 정렬
//            System.out.println(tm);

            //맵에서 다시 꺼내어 반환 타입에 넣는다.
            NgBinResultDto ngBinResultDto = new NgBinResultDto();
            ngBinResultDto.setPartNumber(list.getPartNumber());
            ngBinResultDto.setOperatorId(list.getOperatorId());
            ngBinResultDto.setLotId(list.getLotId());
            ngBinResultDto.setLotInTime(list.getLotInTime());
            ngBinResultDto.setEndTime(list.getEndTime());
            ngBinResultDto.setProcessCode(list.getProcessCode());
            ngBinResultDto.setTesterModel(list.getTesterModel());
            ngBinResultDto.setTesterNumber(list.getTesterNumber());
            ngBinResultDto.setHead(list.getHead());
            ngBinResultDto.setTestCounter(list.getTestCounter());
            ngBinResultDto.setHandlerModel(list.getHandlerModel());
            ngBinResultDto.setBoardId(list.getBoardId());

            Iterator<Integer> keySetIterator = tm.keySet().iterator();
            while (keySetIterator.hasNext()) {
                Integer key = keySetIterator.next();
    //            System.out.println("key: " + key + " value: " + map.get(key));
    //            allColumns += ",\"NGBIN" + key +"\":\"" +map.get(key)+"\"";
                if (key.equals(1)){ngBinResultDto.setNGBIN1(map.get(key));}
                if (key.equals(2)){ngBinResultDto.setNGBIN2(map.get(key));}
                if (key.equals(3)){ngBinResultDto.setNGBIN3(map.get(key));}
                if (key.equals(4)){ngBinResultDto.setNGBIN4(map.get(key));}
                if (key.equals(5)){ngBinResultDto.setNGBIN5(map.get(key));}
                if (key.equals(6)){ngBinResultDto.setNGBIN6(map.get(key));}
                if (key.equals(7)){ngBinResultDto.setNGBIN7(map.get(key));}
                if (key.equals(8)){ngBinResultDto.setNGBIN8(map.get(key));}
                if (key.equals(9)){ngBinResultDto.setNGBIN9(map.get(key));}
                if (key.equals(10)){ngBinResultDto.setNGBIN10(map.get(key));}
                if (key.equals(11)){ngBinResultDto.setNGBIN11(map.get(key));}
                if (key.equals(12)){ngBinResultDto.setNGBIN12(map.get(key));}
                if (key.equals(13)){ngBinResultDto.setNGBIN13(map.get(key));}
                if (key.equals(14)){ngBinResultDto.setNGBIN14(map.get(key));}
                if (key.equals(15)){ngBinResultDto.setNGBIN15(map.get(key));}
                if (key.equals(16)){ngBinResultDto.setNGBIN16(map.get(key));}
                if (key.equals(17)){ngBinResultDto.setNGBIN17(map.get(key));}
                if (key.equals(18)){ngBinResultDto.setNGBIN18(map.get(key));}
                if (key.equals(19)){ngBinResultDto.setNGBIN19(map.get(key));}
                if (key.equals(20)){ngBinResultDto.setNGBIN20(map.get(key));}
                if (key.equals(21)){ngBinResultDto.setNGBIN21(map.get(key));}
                if (key.equals(22)){ngBinResultDto.setNGBIN22(map.get(key));}
                if (key.equals(23)){ngBinResultDto.setNGBIN23(map.get(key));}
                if (key.equals(24)){ngBinResultDto.setNGBIN24(map.get(key));}
                if (key.equals(25)){ngBinResultDto.setNGBIN25(map.get(key));}
                if (key.equals(26)){ngBinResultDto.setNGBIN26(map.get(key));}
                if (key.equals(27)){ngBinResultDto.setNGBIN27(map.get(key));}
                if (key.equals(28)){ngBinResultDto.setNGBIN28(map.get(key));}
                if (key.equals(29)){ngBinResultDto.setNGBIN29(map.get(key));}
                if (key.equals(30)){ngBinResultDto.setNGBIN30(map.get(key));}
                if (key.equals(31)){ngBinResultDto.setNGBIN31(map.get(key));}
                if (key.equals(32)){ngBinResultDto.setNGBIN32(map.get(key));}
                if (key.equals(33)){ngBinResultDto.setNGBIN33(map.get(key));}
                if (key.equals(34)){ngBinResultDto.setNGBIN34(map.get(key));}
                if (key.equals(35)){ngBinResultDto.setNGBIN35(map.get(key));}
                if (key.equals(36)){ngBinResultDto.setNGBIN36(map.get(key));}
                if (key.equals(37)){ngBinResultDto.setNGBIN37(map.get(key));}
                if (key.equals(38)){ngBinResultDto.setNGBIN38(map.get(key));}
                if (key.equals(39)){ngBinResultDto.setNGBIN39(map.get(key));}
                if (key.equals(40)){ngBinResultDto.setNGBIN40(map.get(key));}
                if (key.equals(41)){ngBinResultDto.setNGBIN41(map.get(key));}
                if (key.equals(42)){ngBinResultDto.setNGBIN42(map.get(key));}
                if (key.equals(43)){ngBinResultDto.setNGBIN43(map.get(key));}
                if (key.equals(44)){ngBinResultDto.setNGBIN44(map.get(key));}
                if (key.equals(45)){ngBinResultDto.setNGBIN45(map.get(key));}
                if (key.equals(46)){ngBinResultDto.setNGBIN46(map.get(key));}
                if (key.equals(47)){ngBinResultDto.setNGBIN47(map.get(key));}
                if (key.equals(48)){ngBinResultDto.setNGBIN48(map.get(key));}
                if (key.equals(49)){ngBinResultDto.setNGBIN49(map.get(key));}
                if (key.equals(50)){ngBinResultDto.setNGBIN50(map.get(key));}
                if (key.equals(51)){ngBinResultDto.setNGBIN51(map.get(key));}
                if (key.equals(52)){ngBinResultDto.setNGBIN52(map.get(key));}
                if (key.equals(53)){ngBinResultDto.setNGBIN53(map.get(key));}
                if (key.equals(54)){ngBinResultDto.setNGBIN54(map.get(key));}
                if (key.equals(55)){ngBinResultDto.setNGBIN55(map.get(key));}
                if (key.equals(56)){ngBinResultDto.setNGBIN56(map.get(key));}
                if (key.equals(57)){ngBinResultDto.setNGBIN57(map.get(key));}
                if (key.equals(58)){ngBinResultDto.setNGBIN58(map.get(key));}
                if (key.equals(59)){ngBinResultDto.setNGBIN59(map.get(key));}
                if (key.equals(60)){ngBinResultDto.setNGBIN60(map.get(key));}
                if (key.equals(61)){ngBinResultDto.setNGBIN61(map.get(key));}
                if (key.equals(62)){ngBinResultDto.setNGBIN62(map.get(key));}
                if (key.equals(63)){ngBinResultDto.setNGBIN63(map.get(key));}
                if (key.equals(64)){ngBinResultDto.setNGBIN64(map.get(key));}
                if (key.equals(65)){ngBinResultDto.setNGBIN65(map.get(key));}
                if (key.equals(66)){ngBinResultDto.setNGBIN66(map.get(key));}
                if (key.equals(67)){ngBinResultDto.setNGBIN67(map.get(key));}
                if (key.equals(68)){ngBinResultDto.setNGBIN68(map.get(key));}
                if (key.equals(69)){ngBinResultDto.setNGBIN69(map.get(key));}
                if (key.equals(70)){ngBinResultDto.setNGBIN70(map.get(key));}
                if (key.equals(71)){ngBinResultDto.setNGBIN71(map.get(key));}
                if (key.equals(72)){ngBinResultDto.setNGBIN72(map.get(key));}
                if (key.equals(73)){ngBinResultDto.setNGBIN73(map.get(key));}
                if (key.equals(74)){ngBinResultDto.setNGBIN74(map.get(key));}
                if (key.equals(75)){ngBinResultDto.setNGBIN75(map.get(key));}
                if (key.equals(76)){ngBinResultDto.setNGBIN76(map.get(key));}
                if (key.equals(77)){ngBinResultDto.setNGBIN77(map.get(key));}
                if (key.equals(78)){ngBinResultDto.setNGBIN78(map.get(key));}
                if (key.equals(79)){ngBinResultDto.setNGBIN79(map.get(key));}
                if (key.equals(80)){ngBinResultDto.setNGBIN80(map.get(key));}
                if (key.equals(81)){ngBinResultDto.setNGBIN81(map.get(key));}
                if (key.equals(82)){ngBinResultDto.setNGBIN82(map.get(key));}
                if (key.equals(83)){ngBinResultDto.setNGBIN83(map.get(key));}
                if (key.equals(84)){ngBinResultDto.setNGBIN84(map.get(key));}
                if (key.equals(85)){ngBinResultDto.setNGBIN85(map.get(key));}
                if (key.equals(86)){ngBinResultDto.setNGBIN86(map.get(key));}
                if (key.equals(87)){ngBinResultDto.setNGBIN87(map.get(key));}
                if (key.equals(88)){ngBinResultDto.setNGBIN88(map.get(key));}
                if (key.equals(89)){ngBinResultDto.setNGBIN89(map.get(key));}
                if (key.equals(90)){ngBinResultDto.setNGBIN90(map.get(key));}
                if (key.equals(91)){ngBinResultDto.setNGBIN91(map.get(key));}
                if (key.equals(92)){ngBinResultDto.setNGBIN92(map.get(key));}
                if (key.equals(93)){ngBinResultDto.setNGBIN93(map.get(key));}
                if (key.equals(94)){ngBinResultDto.setNGBIN94(map.get(key));}
                if (key.equals(95)){ngBinResultDto.setNGBIN95(map.get(key));}
                if (key.equals(96)){ngBinResultDto.setNGBIN96(map.get(key));}
                if (key.equals(97)){ngBinResultDto.setNGBIN97(map.get(key));}
                if (key.equals(98)){ngBinResultDto.setNGBIN98(map.get(key));}
                if (key.equals(99)){ngBinResultDto.setNGBIN99(map.get(key));}
                if (key.equals(100)){ngBinResultDto.setNGBIN100(map.get(key));}
                if (key.equals(101)){ngBinResultDto.setNGBIN101(map.get(key));}
                if (key.equals(102)){ngBinResultDto.setNGBIN102(map.get(key));}
                if (key.equals(103)){ngBinResultDto.setNGBIN103(map.get(key));}
                if (key.equals(104)){ngBinResultDto.setNGBIN104(map.get(key));}
                if (key.equals(105)){ngBinResultDto.setNGBIN105(map.get(key));}
                if (key.equals(106)){ngBinResultDto.setNGBIN106(map.get(key));}
                if (key.equals(107)){ngBinResultDto.setNGBIN107(map.get(key));}
                if (key.equals(108)){ngBinResultDto.setNGBIN108(map.get(key));}
                if (key.equals(109)){ngBinResultDto.setNGBIN109(map.get(key));}
                if (key.equals(110)){ngBinResultDto.setNGBIN110(map.get(key));}
                if (key.equals(111)){ngBinResultDto.setNGBIN111(map.get(key));}
                if (key.equals(112)){ngBinResultDto.setNGBIN112(map.get(key));}
                if (key.equals(113)){ngBinResultDto.setNGBIN113(map.get(key));}
                if (key.equals(114)){ngBinResultDto.setNGBIN114(map.get(key));}
                if (key.equals(115)){ngBinResultDto.setNGBIN115(map.get(key));}
                if (key.equals(116)){ngBinResultDto.setNGBIN116(map.get(key));}
                if (key.equals(117)){ngBinResultDto.setNGBIN117(map.get(key));}
                if (key.equals(118)){ngBinResultDto.setNGBIN118(map.get(key));}
                if (key.equals(119)){ngBinResultDto.setNGBIN119(map.get(key));}
                if (key.equals(120)){ngBinResultDto.setNGBIN120(map.get(key));}
                if (key.equals(121)){ngBinResultDto.setNGBIN121(map.get(key));}
                if (key.equals(122)){ngBinResultDto.setNGBIN122(map.get(key));}
                if (key.equals(123)){ngBinResultDto.setNGBIN123(map.get(key));}
                if (key.equals(124)){ngBinResultDto.setNGBIN124(map.get(key));}
                if (key.equals(125)){ngBinResultDto.setNGBIN125(map.get(key));}
                if (key.equals(126)){ngBinResultDto.setNGBIN126(map.get(key));}
                if (key.equals(127)){ngBinResultDto.setNGBIN127(map.get(key));}
                if (key.equals(128)){ngBinResultDto.setNGBIN128(map.get(key));}
                if (key.equals(129)){ngBinResultDto.setNGBIN129(map.get(key));}
                if (key.equals(130)){ngBinResultDto.setNGBIN130(map.get(key));}
                if (key.equals(131)){ngBinResultDto.setNGBIN131(map.get(key));}
                if (key.equals(132)){ngBinResultDto.setNGBIN132(map.get(key));}
                if (key.equals(133)){ngBinResultDto.setNGBIN133(map.get(key));}
                if (key.equals(134)){ngBinResultDto.setNGBIN134(map.get(key));}
                if (key.equals(135)){ngBinResultDto.setNGBIN135(map.get(key));}
                if (key.equals(136)){ngBinResultDto.setNGBIN136(map.get(key));}
                if (key.equals(137)){ngBinResultDto.setNGBIN137(map.get(key));}
                if (key.equals(138)){ngBinResultDto.setNGBIN138(map.get(key));}
                if (key.equals(139)){ngBinResultDto.setNGBIN139(map.get(key));}
                if (key.equals(140)){ngBinResultDto.setNGBIN140(map.get(key));}
                if (key.equals(141)){ngBinResultDto.setNGBIN141(map.get(key));}
                if (key.equals(142)){ngBinResultDto.setNGBIN142(map.get(key));}
                if (key.equals(143)){ngBinResultDto.setNGBIN143(map.get(key));}
                if (key.equals(144)){ngBinResultDto.setNGBIN144(map.get(key));}
                if (key.equals(145)){ngBinResultDto.setNGBIN145(map.get(key));}
                if (key.equals(146)){ngBinResultDto.setNGBIN146(map.get(key));}
                if (key.equals(147)){ngBinResultDto.setNGBIN147(map.get(key));}
                if (key.equals(148)){ngBinResultDto.setNGBIN148(map.get(key));}
                if (key.equals(149)){ngBinResultDto.setNGBIN149(map.get(key));}
                if (key.equals(150)){ngBinResultDto.setNGBIN150(map.get(key));}
                if (key.equals(151)){ngBinResultDto.setNGBIN151(map.get(key));}
                if (key.equals(152)){ngBinResultDto.setNGBIN152(map.get(key));}
                if (key.equals(153)){ngBinResultDto.setNGBIN153(map.get(key));}
                if (key.equals(154)){ngBinResultDto.setNGBIN154(map.get(key));}
                if (key.equals(155)){ngBinResultDto.setNGBIN155(map.get(key));}
                if (key.equals(156)){ngBinResultDto.setNGBIN156(map.get(key));}
                if (key.equals(157)){ngBinResultDto.setNGBIN157(map.get(key));}
                if (key.equals(158)){ngBinResultDto.setNGBIN158(map.get(key));}
                if (key.equals(159)){ngBinResultDto.setNGBIN159(map.get(key));}
                if (key.equals(160)){ngBinResultDto.setNGBIN160(map.get(key));}
                if (key.equals(161)){ngBinResultDto.setNGBIN161(map.get(key));}
                if (key.equals(162)){ngBinResultDto.setNGBIN162(map.get(key));}
                if (key.equals(163)){ngBinResultDto.setNGBIN163(map.get(key));}
                if (key.equals(164)){ngBinResultDto.setNGBIN164(map.get(key));}
                if (key.equals(165)){ngBinResultDto.setNGBIN165(map.get(key));}
                if (key.equals(166)){ngBinResultDto.setNGBIN166(map.get(key));}
                if (key.equals(167)){ngBinResultDto.setNGBIN167(map.get(key));}
                if (key.equals(168)){ngBinResultDto.setNGBIN168(map.get(key));}
                if (key.equals(169)){ngBinResultDto.setNGBIN169(map.get(key));}
                if (key.equals(170)){ngBinResultDto.setNGBIN170(map.get(key));}
                if (key.equals(171)){ngBinResultDto.setNGBIN171(map.get(key));}
                if (key.equals(172)){ngBinResultDto.setNGBIN172(map.get(key));}
                if (key.equals(173)){ngBinResultDto.setNGBIN173(map.get(key));}
                if (key.equals(174)){ngBinResultDto.setNGBIN174(map.get(key));}
                if (key.equals(175)){ngBinResultDto.setNGBIN175(map.get(key));}
                if (key.equals(176)){ngBinResultDto.setNGBIN176(map.get(key));}
                if (key.equals(177)){ngBinResultDto.setNGBIN177(map.get(key));}
                if (key.equals(178)){ngBinResultDto.setNGBIN178(map.get(key));}
                if (key.equals(179)){ngBinResultDto.setNGBIN179(map.get(key));}
                if (key.equals(180)){ngBinResultDto.setNGBIN180(map.get(key));}
                if (key.equals(181)){ngBinResultDto.setNGBIN181(map.get(key));}
                if (key.equals(182)){ngBinResultDto.setNGBIN182(map.get(key));}
                if (key.equals(183)){ngBinResultDto.setNGBIN183(map.get(key));}
                if (key.equals(184)){ngBinResultDto.setNGBIN184(map.get(key));}
                if (key.equals(185)){ngBinResultDto.setNGBIN185(map.get(key));}
                if (key.equals(186)){ngBinResultDto.setNGBIN186(map.get(key));}
                if (key.equals(187)){ngBinResultDto.setNGBIN187(map.get(key));}
                if (key.equals(188)){ngBinResultDto.setNGBIN188(map.get(key));}
                if (key.equals(189)){ngBinResultDto.setNGBIN189(map.get(key));}
                if (key.equals(190)){ngBinResultDto.setNGBIN190(map.get(key));}
                if (key.equals(191)){ngBinResultDto.setNGBIN191(map.get(key));}
                if (key.equals(192)){ngBinResultDto.setNGBIN192(map.get(key));}
                if (key.equals(193)){ngBinResultDto.setNGBIN193(map.get(key));}
                if (key.equals(194)){ngBinResultDto.setNGBIN194(map.get(key));}
                if (key.equals(195)){ngBinResultDto.setNGBIN195(map.get(key));}
                if (key.equals(196)){ngBinResultDto.setNGBIN196(map.get(key));}
                if (key.equals(197)){ngBinResultDto.setNGBIN197(map.get(key));}
                if (key.equals(198)){ngBinResultDto.setNGBIN198(map.get(key));}
                if (key.equals(199)){ngBinResultDto.setNGBIN199(map.get(key));}
                if (key.equals(200)){ngBinResultDto.setNGBIN200(map.get(key));}
                if (key.equals(201)){ngBinResultDto.setNGBIN201(map.get(key));}
                if (key.equals(202)){ngBinResultDto.setNGBIN202(map.get(key));}
                if (key.equals(203)){ngBinResultDto.setNGBIN203(map.get(key));}
                if (key.equals(204)){ngBinResultDto.setNGBIN204(map.get(key));}
                if (key.equals(205)){ngBinResultDto.setNGBIN205(map.get(key));}
                if (key.equals(206)){ngBinResultDto.setNGBIN206(map.get(key));}
                if (key.equals(207)){ngBinResultDto.setNGBIN207(map.get(key));}
                if (key.equals(208)){ngBinResultDto.setNGBIN208(map.get(key));}
                if (key.equals(209)){ngBinResultDto.setNGBIN209(map.get(key));}
                if (key.equals(210)){ngBinResultDto.setNGBIN210(map.get(key));}
                if (key.equals(211)){ngBinResultDto.setNGBIN211(map.get(key));}
                if (key.equals(212)){ngBinResultDto.setNGBIN212(map.get(key));}
                if (key.equals(213)){ngBinResultDto.setNGBIN213(map.get(key));}
                if (key.equals(214)){ngBinResultDto.setNGBIN214(map.get(key));}
                if (key.equals(215)){ngBinResultDto.setNGBIN215(map.get(key));}
                if (key.equals(216)){ngBinResultDto.setNGBIN216(map.get(key));}
                if (key.equals(217)){ngBinResultDto.setNGBIN217(map.get(key));}
                if (key.equals(218)){ngBinResultDto.setNGBIN218(map.get(key));}
                if (key.equals(219)){ngBinResultDto.setNGBIN219(map.get(key));}
                if (key.equals(220)){ngBinResultDto.setNGBIN220(map.get(key));}
                if (key.equals(221)){ngBinResultDto.setNGBIN221(map.get(key));}
                if (key.equals(222)){ngBinResultDto.setNGBIN222(map.get(key));}
                if (key.equals(223)){ngBinResultDto.setNGBIN223(map.get(key));}
                if (key.equals(224)){ngBinResultDto.setNGBIN224(map.get(key));}
                if (key.equals(225)){ngBinResultDto.setNGBIN225(map.get(key));}
                if (key.equals(226)){ngBinResultDto.setNGBIN226(map.get(key));}
                if (key.equals(227)){ngBinResultDto.setNGBIN227(map.get(key));}
                if (key.equals(228)){ngBinResultDto.setNGBIN228(map.get(key));}
                if (key.equals(229)){ngBinResultDto.setNGBIN229(map.get(key));}
                if (key.equals(230)){ngBinResultDto.setNGBIN230(map.get(key));}
                if (key.equals(231)){ngBinResultDto.setNGBIN231(map.get(key));}
                if (key.equals(232)){ngBinResultDto.setNGBIN232(map.get(key));}
                if (key.equals(233)){ngBinResultDto.setNGBIN233(map.get(key));}
                if (key.equals(234)){ngBinResultDto.setNGBIN234(map.get(key));}
                if (key.equals(235)){ngBinResultDto.setNGBIN235(map.get(key));}
                if (key.equals(236)){ngBinResultDto.setNGBIN236(map.get(key));}
                if (key.equals(237)){ngBinResultDto.setNGBIN237(map.get(key));}
                if (key.equals(238)){ngBinResultDto.setNGBIN238(map.get(key));}
                if (key.equals(239)){ngBinResultDto.setNGBIN239(map.get(key));}
                if (key.equals(240)){ngBinResultDto.setNGBIN240(map.get(key));}
                if (key.equals(241)){ngBinResultDto.setNGBIN241(map.get(key));}
                if (key.equals(242)){ngBinResultDto.setNGBIN242(map.get(key));}
                if (key.equals(243)){ngBinResultDto.setNGBIN243(map.get(key));}
                if (key.equals(244)){ngBinResultDto.setNGBIN244(map.get(key));}
                if (key.equals(245)){ngBinResultDto.setNGBIN245(map.get(key));}
                if (key.equals(246)){ngBinResultDto.setNGBIN246(map.get(key));}
                if (key.equals(247)){ngBinResultDto.setNGBIN247(map.get(key));}
                if (key.equals(248)){ngBinResultDto.setNGBIN248(map.get(key));}
                if (key.equals(249)){ngBinResultDto.setNGBIN249(map.get(key));}
                if (key.equals(250)){ngBinResultDto.setNGBIN250(map.get(key));}
                if (key.equals(251)){ngBinResultDto.setNGBIN251(map.get(key));}
                if (key.equals(252)){ngBinResultDto.setNGBIN252(map.get(key));}
                if (key.equals(253)){ngBinResultDto.setNGBIN253(map.get(key));}
                if (key.equals(254)){ngBinResultDto.setNGBIN254(map.get(key));}
                if (key.equals(255)){ngBinResultDto.setNGBIN255(map.get(key));}
                if (key.equals(256)){ngBinResultDto.setNGBIN256(map.get(key));}
                if (key.equals(257)){ngBinResultDto.setNGBIN257(map.get(key));}
                if (key.equals(258)){ngBinResultDto.setNGBIN258(map.get(key));}
                if (key.equals(259)){ngBinResultDto.setNGBIN259(map.get(key));}
                if (key.equals(260)){ngBinResultDto.setNGBIN260(map.get(key));}
                if (key.equals(261)){ngBinResultDto.setNGBIN261(map.get(key));}
                if (key.equals(262)){ngBinResultDto.setNGBIN262(map.get(key));}
                if (key.equals(263)){ngBinResultDto.setNGBIN263(map.get(key));}
                if (key.equals(264)){ngBinResultDto.setNGBIN264(map.get(key));}
                if (key.equals(265)){ngBinResultDto.setNGBIN265(map.get(key));}
                if (key.equals(266)){ngBinResultDto.setNGBIN266(map.get(key));}
                if (key.equals(267)){ngBinResultDto.setNGBIN267(map.get(key));}
                if (key.equals(268)){ngBinResultDto.setNGBIN268(map.get(key));}
                if (key.equals(269)){ngBinResultDto.setNGBIN269(map.get(key));}
                if (key.equals(270)){ngBinResultDto.setNGBIN270(map.get(key));}
                if (key.equals(271)){ngBinResultDto.setNGBIN271(map.get(key));}
                if (key.equals(272)){ngBinResultDto.setNGBIN272(map.get(key));}
                if (key.equals(273)){ngBinResultDto.setNGBIN273(map.get(key));}
                if (key.equals(274)){ngBinResultDto.setNGBIN274(map.get(key));}
                if (key.equals(275)){ngBinResultDto.setNGBIN275(map.get(key));}
                if (key.equals(276)){ngBinResultDto.setNGBIN276(map.get(key));}
                if (key.equals(277)){ngBinResultDto.setNGBIN277(map.get(key));}
                if (key.equals(278)){ngBinResultDto.setNGBIN278(map.get(key));}
                if (key.equals(279)){ngBinResultDto.setNGBIN279(map.get(key));}
                if (key.equals(280)){ngBinResultDto.setNGBIN280(map.get(key));}
                if (key.equals(281)){ngBinResultDto.setNGBIN281(map.get(key));}
                if (key.equals(282)){ngBinResultDto.setNGBIN282(map.get(key));}
                if (key.equals(283)){ngBinResultDto.setNGBIN283(map.get(key));}
                if (key.equals(284)){ngBinResultDto.setNGBIN284(map.get(key));}
                if (key.equals(285)){ngBinResultDto.setNGBIN285(map.get(key));}
                if (key.equals(286)){ngBinResultDto.setNGBIN286(map.get(key));}
                if (key.equals(287)){ngBinResultDto.setNGBIN287(map.get(key));}
                if (key.equals(288)){ngBinResultDto.setNGBIN288(map.get(key));}
                if (key.equals(289)){ngBinResultDto.setNGBIN289(map.get(key));}
                if (key.equals(290)){ngBinResultDto.setNGBIN290(map.get(key));}
                if (key.equals(291)){ngBinResultDto.setNGBIN291(map.get(key));}
                if (key.equals(292)){ngBinResultDto.setNGBIN292(map.get(key));}
                if (key.equals(293)){ngBinResultDto.setNGBIN293(map.get(key));}
                if (key.equals(294)){ngBinResultDto.setNGBIN294(map.get(key));}
                if (key.equals(295)){ngBinResultDto.setNGBIN295(map.get(key));}
                if (key.equals(296)){ngBinResultDto.setNGBIN296(map.get(key));}
                if (key.equals(297)){ngBinResultDto.setNGBIN297(map.get(key));}
                if (key.equals(298)){ngBinResultDto.setNGBIN298(map.get(key));}
                if (key.equals(299)){ngBinResultDto.setNGBIN299(map.get(key));}
                if (key.equals(300)){ngBinResultDto.setNGBIN300(map.get(key));}
                if (key.equals(301)){ngBinResultDto.setNGBIN301(map.get(key));}
                if (key.equals(302)){ngBinResultDto.setNGBIN302(map.get(key));}
                if (key.equals(303)){ngBinResultDto.setNGBIN303(map.get(key));}
                if (key.equals(304)){ngBinResultDto.setNGBIN304(map.get(key));}
                if (key.equals(305)){ngBinResultDto.setNGBIN305(map.get(key));}
                if (key.equals(306)){ngBinResultDto.setNGBIN306(map.get(key));}
                if (key.equals(307)){ngBinResultDto.setNGBIN307(map.get(key));}
                if (key.equals(308)){ngBinResultDto.setNGBIN308(map.get(key));}
                if (key.equals(309)){ngBinResultDto.setNGBIN309(map.get(key));}
                if (key.equals(310)){ngBinResultDto.setNGBIN310(map.get(key));}
                if (key.equals(311)){ngBinResultDto.setNGBIN311(map.get(key));}
                if (key.equals(312)){ngBinResultDto.setNGBIN312(map.get(key));}
                if (key.equals(313)){ngBinResultDto.setNGBIN313(map.get(key));}
                if (key.equals(314)){ngBinResultDto.setNGBIN314(map.get(key));}
                if (key.equals(315)){ngBinResultDto.setNGBIN315(map.get(key));}
                if (key.equals(316)){ngBinResultDto.setNGBIN316(map.get(key));}
                if (key.equals(317)){ngBinResultDto.setNGBIN317(map.get(key));}
                if (key.equals(318)){ngBinResultDto.setNGBIN318(map.get(key));}
                if (key.equals(319)){ngBinResultDto.setNGBIN319(map.get(key));}
                if (key.equals(320)){ngBinResultDto.setNGBIN320(map.get(key));}
                if (key.equals(321)){ngBinResultDto.setNGBIN321(map.get(key));}
                if (key.equals(322)){ngBinResultDto.setNGBIN322(map.get(key));}
                if (key.equals(323)){ngBinResultDto.setNGBIN323(map.get(key));}
                if (key.equals(324)){ngBinResultDto.setNGBIN324(map.get(key));}
                if (key.equals(325)){ngBinResultDto.setNGBIN325(map.get(key));}
                if (key.equals(326)){ngBinResultDto.setNGBIN326(map.get(key));}
                if (key.equals(327)){ngBinResultDto.setNGBIN327(map.get(key));}
                if (key.equals(328)){ngBinResultDto.setNGBIN328(map.get(key));}
                if (key.equals(329)){ngBinResultDto.setNGBIN329(map.get(key));}
                if (key.equals(330)){ngBinResultDto.setNGBIN330(map.get(key));}
                if (key.equals(331)){ngBinResultDto.setNGBIN331(map.get(key));}
                if (key.equals(332)){ngBinResultDto.setNGBIN332(map.get(key));}
                if (key.equals(333)){ngBinResultDto.setNGBIN333(map.get(key));}
                if (key.equals(334)){ngBinResultDto.setNGBIN334(map.get(key));}
                if (key.equals(335)){ngBinResultDto.setNGBIN335(map.get(key));}
                if (key.equals(336)){ngBinResultDto.setNGBIN336(map.get(key));}
                if (key.equals(337)){ngBinResultDto.setNGBIN337(map.get(key));}
                if (key.equals(338)){ngBinResultDto.setNGBIN338(map.get(key));}
                if (key.equals(339)){ngBinResultDto.setNGBIN339(map.get(key));}
                if (key.equals(340)){ngBinResultDto.setNGBIN340(map.get(key));}
                if (key.equals(341)){ngBinResultDto.setNGBIN341(map.get(key));}
                if (key.equals(342)){ngBinResultDto.setNGBIN342(map.get(key));}
                if (key.equals(343)){ngBinResultDto.setNGBIN343(map.get(key));}
                if (key.equals(344)){ngBinResultDto.setNGBIN344(map.get(key));}
                if (key.equals(345)){ngBinResultDto.setNGBIN345(map.get(key));}
                if (key.equals(346)){ngBinResultDto.setNGBIN346(map.get(key));}
                if (key.equals(347)){ngBinResultDto.setNGBIN347(map.get(key));}
                if (key.equals(348)){ngBinResultDto.setNGBIN348(map.get(key));}
                if (key.equals(349)){ngBinResultDto.setNGBIN349(map.get(key));}
                if (key.equals(350)){ngBinResultDto.setNGBIN350(map.get(key));}
                if (key.equals(351)){ngBinResultDto.setNGBIN351(map.get(key));}
                if (key.equals(352)){ngBinResultDto.setNGBIN352(map.get(key));}
                if (key.equals(353)){ngBinResultDto.setNGBIN353(map.get(key));}
                if (key.equals(354)){ngBinResultDto.setNGBIN354(map.get(key));}
                if (key.equals(355)){ngBinResultDto.setNGBIN355(map.get(key));}
                if (key.equals(356)){ngBinResultDto.setNGBIN356(map.get(key));}
                if (key.equals(357)){ngBinResultDto.setNGBIN357(map.get(key));}
                if (key.equals(358)){ngBinResultDto.setNGBIN358(map.get(key));}
                if (key.equals(359)){ngBinResultDto.setNGBIN359(map.get(key));}
                if (key.equals(360)){ngBinResultDto.setNGBIN360(map.get(key));}
                if (key.equals(361)){ngBinResultDto.setNGBIN361(map.get(key));}
                if (key.equals(362)){ngBinResultDto.setNGBIN362(map.get(key));}
                if (key.equals(363)){ngBinResultDto.setNGBIN363(map.get(key));}
                if (key.equals(364)){ngBinResultDto.setNGBIN364(map.get(key));}
                if (key.equals(365)){ngBinResultDto.setNGBIN365(map.get(key));}
                if (key.equals(366)){ngBinResultDto.setNGBIN366(map.get(key));}
                if (key.equals(367)){ngBinResultDto.setNGBIN367(map.get(key));}
                if (key.equals(368)){ngBinResultDto.setNGBIN368(map.get(key));}
                if (key.equals(369)){ngBinResultDto.setNGBIN369(map.get(key));}
                if (key.equals(370)){ngBinResultDto.setNGBIN370(map.get(key));}
                if (key.equals(371)){ngBinResultDto.setNGBIN371(map.get(key));}
                if (key.equals(372)){ngBinResultDto.setNGBIN372(map.get(key));}
                if (key.equals(373)){ngBinResultDto.setNGBIN373(map.get(key));}
                if (key.equals(374)){ngBinResultDto.setNGBIN374(map.get(key));}
                if (key.equals(375)){ngBinResultDto.setNGBIN375(map.get(key));}
                if (key.equals(376)){ngBinResultDto.setNGBIN376(map.get(key));}
                if (key.equals(377)){ngBinResultDto.setNGBIN377(map.get(key));}
                if (key.equals(378)){ngBinResultDto.setNGBIN378(map.get(key));}
                if (key.equals(379)){ngBinResultDto.setNGBIN379(map.get(key));}
                if (key.equals(380)){ngBinResultDto.setNGBIN380(map.get(key));}
                if (key.equals(381)){ngBinResultDto.setNGBIN381(map.get(key));}
                if (key.equals(382)){ngBinResultDto.setNGBIN382(map.get(key));}
                if (key.equals(383)){ngBinResultDto.setNGBIN383(map.get(key));}
                if (key.equals(384)){ngBinResultDto.setNGBIN384(map.get(key));}
                if (key.equals(385)){ngBinResultDto.setNGBIN385(map.get(key));}
                if (key.equals(386)){ngBinResultDto.setNGBIN386(map.get(key));}
                if (key.equals(387)){ngBinResultDto.setNGBIN387(map.get(key));}
                if (key.equals(388)){ngBinResultDto.setNGBIN388(map.get(key));}
                if (key.equals(389)){ngBinResultDto.setNGBIN389(map.get(key));}
                if (key.equals(390)){ngBinResultDto.setNGBIN390(map.get(key));}
                if (key.equals(391)){ngBinResultDto.setNGBIN391(map.get(key));}
                if (key.equals(392)){ngBinResultDto.setNGBIN392(map.get(key));}
                if (key.equals(393)){ngBinResultDto.setNGBIN393(map.get(key));}
                if (key.equals(394)){ngBinResultDto.setNGBIN394(map.get(key));}
                if (key.equals(395)){ngBinResultDto.setNGBIN395(map.get(key));}
                if (key.equals(396)){ngBinResultDto.setNGBIN396(map.get(key));}
                if (key.equals(397)){ngBinResultDto.setNGBIN397(map.get(key));}
                if (key.equals(398)){ngBinResultDto.setNGBIN398(map.get(key));}
                if (key.equals(399)){ngBinResultDto.setNGBIN399(map.get(key));}
                if (key.equals(400)){ngBinResultDto.setNGBIN400(map.get(key));}
                if (key.equals(401)){ngBinResultDto.setNGBIN401(map.get(key));}
                if (key.equals(402)){ngBinResultDto.setNGBIN402(map.get(key));}
                if (key.equals(403)){ngBinResultDto.setNGBIN403(map.get(key));}
                if (key.equals(404)){ngBinResultDto.setNGBIN404(map.get(key));}
                if (key.equals(405)){ngBinResultDto.setNGBIN405(map.get(key));}
                if (key.equals(406)){ngBinResultDto.setNGBIN406(map.get(key));}
                if (key.equals(407)){ngBinResultDto.setNGBIN407(map.get(key));}
                if (key.equals(408)){ngBinResultDto.setNGBIN408(map.get(key));}
                if (key.equals(409)){ngBinResultDto.setNGBIN409(map.get(key));}
                if (key.equals(410)){ngBinResultDto.setNGBIN410(map.get(key));}
                if (key.equals(411)){ngBinResultDto.setNGBIN411(map.get(key));}
                if (key.equals(412)){ngBinResultDto.setNGBIN412(map.get(key));}
                if (key.equals(413)){ngBinResultDto.setNGBIN413(map.get(key));}
                if (key.equals(414)){ngBinResultDto.setNGBIN414(map.get(key));}
                if (key.equals(415)){ngBinResultDto.setNGBIN415(map.get(key));}
                if (key.equals(416)){ngBinResultDto.setNGBIN416(map.get(key));}
                if (key.equals(417)){ngBinResultDto.setNGBIN417(map.get(key));}
                if (key.equals(418)){ngBinResultDto.setNGBIN418(map.get(key));}
                if (key.equals(419)){ngBinResultDto.setNGBIN419(map.get(key));}
                if (key.equals(420)){ngBinResultDto.setNGBIN420(map.get(key));}
                if (key.equals(421)){ngBinResultDto.setNGBIN421(map.get(key));}
                if (key.equals(422)){ngBinResultDto.setNGBIN422(map.get(key));}
                if (key.equals(423)){ngBinResultDto.setNGBIN423(map.get(key));}
                if (key.equals(424)){ngBinResultDto.setNGBIN424(map.get(key));}
                if (key.equals(425)){ngBinResultDto.setNGBIN425(map.get(key));}
                if (key.equals(426)){ngBinResultDto.setNGBIN426(map.get(key));}
                if (key.equals(427)){ngBinResultDto.setNGBIN427(map.get(key));}
                if (key.equals(428)){ngBinResultDto.setNGBIN428(map.get(key));}
                if (key.equals(429)){ngBinResultDto.setNGBIN429(map.get(key));}
                if (key.equals(430)){ngBinResultDto.setNGBIN430(map.get(key));}
                if (key.equals(431)){ngBinResultDto.setNGBIN431(map.get(key));}
                if (key.equals(432)){ngBinResultDto.setNGBIN432(map.get(key));}
                if (key.equals(433)){ngBinResultDto.setNGBIN433(map.get(key));}
                if (key.equals(434)){ngBinResultDto.setNGBIN434(map.get(key));}
                if (key.equals(435)){ngBinResultDto.setNGBIN435(map.get(key));}
                if (key.equals(436)){ngBinResultDto.setNGBIN436(map.get(key));}
                if (key.equals(437)){ngBinResultDto.setNGBIN437(map.get(key));}
                if (key.equals(438)){ngBinResultDto.setNGBIN438(map.get(key));}
                if (key.equals(439)){ngBinResultDto.setNGBIN439(map.get(key));}
                if (key.equals(440)){ngBinResultDto.setNGBIN440(map.get(key));}
                if (key.equals(441)){ngBinResultDto.setNGBIN441(map.get(key));}
                if (key.equals(442)){ngBinResultDto.setNGBIN442(map.get(key));}
                if (key.equals(443)){ngBinResultDto.setNGBIN443(map.get(key));}
                if (key.equals(444)){ngBinResultDto.setNGBIN444(map.get(key));}
                if (key.equals(445)){ngBinResultDto.setNGBIN445(map.get(key));}
                if (key.equals(446)){ngBinResultDto.setNGBIN446(map.get(key));}
                if (key.equals(447)){ngBinResultDto.setNGBIN447(map.get(key));}
                if (key.equals(448)){ngBinResultDto.setNGBIN448(map.get(key));}
                if (key.equals(449)){ngBinResultDto.setNGBIN449(map.get(key));}
                if (key.equals(450)){ngBinResultDto.setNGBIN450(map.get(key));}
                if (key.equals(451)){ngBinResultDto.setNGBIN451(map.get(key));}
                if (key.equals(452)){ngBinResultDto.setNGBIN452(map.get(key));}
                if (key.equals(453)){ngBinResultDto.setNGBIN453(map.get(key));}
                if (key.equals(454)){ngBinResultDto.setNGBIN454(map.get(key));}
                if (key.equals(455)){ngBinResultDto.setNGBIN455(map.get(key));}
                if (key.equals(456)){ngBinResultDto.setNGBIN456(map.get(key));}
                if (key.equals(457)){ngBinResultDto.setNGBIN457(map.get(key));}
                if (key.equals(458)){ngBinResultDto.setNGBIN458(map.get(key));}
                if (key.equals(459)){ngBinResultDto.setNGBIN459(map.get(key));}
                if (key.equals(460)){ngBinResultDto.setNGBIN460(map.get(key));}
                if (key.equals(461)){ngBinResultDto.setNGBIN461(map.get(key));}
                if (key.equals(462)){ngBinResultDto.setNGBIN462(map.get(key));}
                if (key.equals(463)){ngBinResultDto.setNGBIN463(map.get(key));}
                if (key.equals(464)){ngBinResultDto.setNGBIN464(map.get(key));}
                if (key.equals(465)){ngBinResultDto.setNGBIN465(map.get(key));}
                if (key.equals(466)){ngBinResultDto.setNGBIN466(map.get(key));}
                if (key.equals(467)){ngBinResultDto.setNGBIN467(map.get(key));}
                if (key.equals(468)){ngBinResultDto.setNGBIN468(map.get(key));}
                if (key.equals(469)){ngBinResultDto.setNGBIN469(map.get(key));}
                if (key.equals(470)){ngBinResultDto.setNGBIN470(map.get(key));}
                if (key.equals(471)){ngBinResultDto.setNGBIN471(map.get(key));}
                if (key.equals(472)){ngBinResultDto.setNGBIN472(map.get(key));}
                if (key.equals(473)){ngBinResultDto.setNGBIN473(map.get(key));}
                if (key.equals(474)){ngBinResultDto.setNGBIN474(map.get(key));}
                if (key.equals(475)){ngBinResultDto.setNGBIN475(map.get(key));}
                if (key.equals(476)){ngBinResultDto.setNGBIN476(map.get(key));}
                if (key.equals(477)){ngBinResultDto.setNGBIN477(map.get(key));}
                if (key.equals(478)){ngBinResultDto.setNGBIN478(map.get(key));}
                if (key.equals(479)){ngBinResultDto.setNGBIN479(map.get(key));}
                if (key.equals(480)){ngBinResultDto.setNGBIN480(map.get(key));}
                if (key.equals(481)){ngBinResultDto.setNGBIN481(map.get(key));}
                if (key.equals(482)){ngBinResultDto.setNGBIN482(map.get(key));}
                if (key.equals(483)){ngBinResultDto.setNGBIN483(map.get(key));}
                if (key.equals(484)){ngBinResultDto.setNGBIN484(map.get(key));}
                if (key.equals(485)){ngBinResultDto.setNGBIN485(map.get(key));}
                if (key.equals(486)){ngBinResultDto.setNGBIN486(map.get(key));}
                if (key.equals(487)){ngBinResultDto.setNGBIN487(map.get(key));}
                if (key.equals(488)){ngBinResultDto.setNGBIN488(map.get(key));}
                if (key.equals(489)){ngBinResultDto.setNGBIN489(map.get(key));}
                if (key.equals(490)){ngBinResultDto.setNGBIN490(map.get(key));}
                if (key.equals(491)){ngBinResultDto.setNGBIN491(map.get(key));}
                if (key.equals(492)){ngBinResultDto.setNGBIN492(map.get(key));}
                if (key.equals(493)){ngBinResultDto.setNGBIN493(map.get(key));}
                if (key.equals(494)){ngBinResultDto.setNGBIN494(map.get(key));}
                if (key.equals(495)){ngBinResultDto.setNGBIN495(map.get(key));}
                if (key.equals(496)){ngBinResultDto.setNGBIN496(map.get(key));}
                if (key.equals(497)){ngBinResultDto.setNGBIN497(map.get(key));}
                if (key.equals(498)){ngBinResultDto.setNGBIN498(map.get(key));}
                if (key.equals(499)){ngBinResultDto.setNGBIN499(map.get(key));}
                if (key.equals(500)){ngBinResultDto.setNGBIN500(map.get(key));}
                if (key.equals(501)){ngBinResultDto.setNGBIN501(map.get(key));}
                if (key.equals(502)){ngBinResultDto.setNGBIN502(map.get(key));}
                if (key.equals(503)){ngBinResultDto.setNGBIN503(map.get(key));}
                if (key.equals(504)){ngBinResultDto.setNGBIN504(map.get(key));}
                if (key.equals(505)){ngBinResultDto.setNGBIN505(map.get(key));}
                if (key.equals(506)){ngBinResultDto.setNGBIN506(map.get(key));}
                if (key.equals(507)){ngBinResultDto.setNGBIN507(map.get(key));}
                if (key.equals(508)){ngBinResultDto.setNGBIN508(map.get(key));}
                if (key.equals(509)){ngBinResultDto.setNGBIN509(map.get(key));}
                if (key.equals(510)){ngBinResultDto.setNGBIN510(map.get(key));}
                if (key.equals(511)){ngBinResultDto.setNGBIN511(map.get(key));}
                if (key.equals(512)){ngBinResultDto.setNGBIN512(map.get(key));}
                if (key.equals(513)){ngBinResultDto.setNGBIN513(map.get(key));}
                if (key.equals(514)){ngBinResultDto.setNGBIN514(map.get(key));}
                if (key.equals(515)){ngBinResultDto.setNGBIN515(map.get(key));}
                if (key.equals(516)){ngBinResultDto.setNGBIN516(map.get(key));}
                if (key.equals(517)){ngBinResultDto.setNGBIN517(map.get(key));}
                if (key.equals(518)){ngBinResultDto.setNGBIN518(map.get(key));}
                if (key.equals(519)){ngBinResultDto.setNGBIN519(map.get(key));}
                if (key.equals(520)){ngBinResultDto.setNGBIN520(map.get(key));}
                if (key.equals(521)){ngBinResultDto.setNGBIN521(map.get(key));}
                if (key.equals(522)){ngBinResultDto.setNGBIN522(map.get(key));}
                if (key.equals(523)){ngBinResultDto.setNGBIN523(map.get(key));}
                if (key.equals(524)){ngBinResultDto.setNGBIN524(map.get(key));}
                if (key.equals(525)){ngBinResultDto.setNGBIN525(map.get(key));}
                if (key.equals(526)){ngBinResultDto.setNGBIN526(map.get(key));}
                if (key.equals(527)){ngBinResultDto.setNGBIN527(map.get(key));}
                if (key.equals(528)){ngBinResultDto.setNGBIN528(map.get(key));}
                if (key.equals(529)){ngBinResultDto.setNGBIN529(map.get(key));}
                if (key.equals(530)){ngBinResultDto.setNGBIN530(map.get(key));}
                if (key.equals(531)){ngBinResultDto.setNGBIN531(map.get(key));}
                if (key.equals(532)){ngBinResultDto.setNGBIN532(map.get(key));}
                if (key.equals(533)){ngBinResultDto.setNGBIN533(map.get(key));}
                if (key.equals(534)){ngBinResultDto.setNGBIN534(map.get(key));}
                if (key.equals(535)){ngBinResultDto.setNGBIN535(map.get(key));}
                if (key.equals(536)){ngBinResultDto.setNGBIN536(map.get(key));}
                if (key.equals(537)){ngBinResultDto.setNGBIN537(map.get(key));}
                if (key.equals(538)){ngBinResultDto.setNGBIN538(map.get(key));}
                if (key.equals(539)){ngBinResultDto.setNGBIN539(map.get(key));}
                if (key.equals(540)){ngBinResultDto.setNGBIN540(map.get(key));}
                if (key.equals(541)){ngBinResultDto.setNGBIN541(map.get(key));}
                if (key.equals(542)){ngBinResultDto.setNGBIN542(map.get(key));}
                if (key.equals(543)){ngBinResultDto.setNGBIN543(map.get(key));}
                if (key.equals(544)){ngBinResultDto.setNGBIN544(map.get(key));}
                if (key.equals(545)){ngBinResultDto.setNGBIN545(map.get(key));}
                if (key.equals(546)){ngBinResultDto.setNGBIN546(map.get(key));}
                if (key.equals(547)){ngBinResultDto.setNGBIN547(map.get(key));}
                if (key.equals(548)){ngBinResultDto.setNGBIN548(map.get(key));}
                if (key.equals(549)){ngBinResultDto.setNGBIN549(map.get(key));}
                if (key.equals(550)){ngBinResultDto.setNGBIN550(map.get(key));}
                if (key.equals(551)){ngBinResultDto.setNGBIN551(map.get(key));}
                if (key.equals(552)){ngBinResultDto.setNGBIN552(map.get(key));}
                if (key.equals(553)){ngBinResultDto.setNGBIN553(map.get(key));}
                if (key.equals(554)){ngBinResultDto.setNGBIN554(map.get(key));}
                if (key.equals(555)){ngBinResultDto.setNGBIN555(map.get(key));}
                if (key.equals(556)){ngBinResultDto.setNGBIN556(map.get(key));}
                if (key.equals(557)){ngBinResultDto.setNGBIN557(map.get(key));}
                if (key.equals(558)){ngBinResultDto.setNGBIN558(map.get(key));}
                if (key.equals(559)){ngBinResultDto.setNGBIN559(map.get(key));}
                if (key.equals(560)){ngBinResultDto.setNGBIN560(map.get(key));}
                if (key.equals(561)){ngBinResultDto.setNGBIN561(map.get(key));}
                if (key.equals(562)){ngBinResultDto.setNGBIN562(map.get(key));}
                if (key.equals(563)){ngBinResultDto.setNGBIN563(map.get(key));}
                if (key.equals(564)){ngBinResultDto.setNGBIN564(map.get(key));}
                if (key.equals(565)){ngBinResultDto.setNGBIN565(map.get(key));}
                if (key.equals(566)){ngBinResultDto.setNGBIN566(map.get(key));}
                if (key.equals(567)){ngBinResultDto.setNGBIN567(map.get(key));}
                if (key.equals(568)){ngBinResultDto.setNGBIN568(map.get(key));}
                if (key.equals(569)){ngBinResultDto.setNGBIN569(map.get(key));}
                if (key.equals(570)){ngBinResultDto.setNGBIN570(map.get(key));}
                if (key.equals(571)){ngBinResultDto.setNGBIN571(map.get(key));}
                if (key.equals(572)){ngBinResultDto.setNGBIN572(map.get(key));}
                if (key.equals(573)){ngBinResultDto.setNGBIN573(map.get(key));}
                if (key.equals(574)){ngBinResultDto.setNGBIN574(map.get(key));}
                if (key.equals(575)){ngBinResultDto.setNGBIN575(map.get(key));}
                if (key.equals(576)){ngBinResultDto.setNGBIN576(map.get(key));}
                if (key.equals(577)){ngBinResultDto.setNGBIN577(map.get(key));}
                if (key.equals(578)){ngBinResultDto.setNGBIN578(map.get(key));}
                if (key.equals(579)){ngBinResultDto.setNGBIN579(map.get(key));}
                if (key.equals(580)){ngBinResultDto.setNGBIN580(map.get(key));}
                if (key.equals(581)){ngBinResultDto.setNGBIN581(map.get(key));}
                if (key.equals(582)){ngBinResultDto.setNGBIN582(map.get(key));}
                if (key.equals(583)){ngBinResultDto.setNGBIN583(map.get(key));}
                if (key.equals(584)){ngBinResultDto.setNGBIN584(map.get(key));}
                if (key.equals(585)){ngBinResultDto.setNGBIN585(map.get(key));}
                if (key.equals(586)){ngBinResultDto.setNGBIN586(map.get(key));}
                if (key.equals(587)){ngBinResultDto.setNGBIN587(map.get(key));}
                if (key.equals(588)){ngBinResultDto.setNGBIN588(map.get(key));}
                if (key.equals(589)){ngBinResultDto.setNGBIN589(map.get(key));}
                if (key.equals(590)){ngBinResultDto.setNGBIN590(map.get(key));}
                if (key.equals(591)){ngBinResultDto.setNGBIN591(map.get(key));}
                if (key.equals(592)){ngBinResultDto.setNGBIN592(map.get(key));}
                if (key.equals(593)){ngBinResultDto.setNGBIN593(map.get(key));}
                if (key.equals(594)){ngBinResultDto.setNGBIN594(map.get(key));}
                if (key.equals(595)){ngBinResultDto.setNGBIN595(map.get(key));}
                if (key.equals(596)){ngBinResultDto.setNGBIN596(map.get(key));}
                if (key.equals(597)){ngBinResultDto.setNGBIN597(map.get(key));}
                if (key.equals(598)){ngBinResultDto.setNGBIN598(map.get(key));}
                if (key.equals(599)){ngBinResultDto.setNGBIN599(map.get(key));}
                if (key.equals(600)){ngBinResultDto.setNGBIN600(map.get(key));}
                if (key.equals(601)){ngBinResultDto.setNGBIN601(map.get(key));}
                if (key.equals(602)){ngBinResultDto.setNGBIN602(map.get(key));}
                if (key.equals(603)){ngBinResultDto.setNGBIN603(map.get(key));}
                if (key.equals(604)){ngBinResultDto.setNGBIN604(map.get(key));}
                if (key.equals(605)){ngBinResultDto.setNGBIN605(map.get(key));}
                if (key.equals(606)){ngBinResultDto.setNGBIN606(map.get(key));}
                if (key.equals(607)){ngBinResultDto.setNGBIN607(map.get(key));}
                if (key.equals(608)){ngBinResultDto.setNGBIN608(map.get(key));}
                if (key.equals(609)){ngBinResultDto.setNGBIN609(map.get(key));}
                if (key.equals(610)){ngBinResultDto.setNGBIN610(map.get(key));}
                if (key.equals(611)){ngBinResultDto.setNGBIN611(map.get(key));}
                if (key.equals(612)){ngBinResultDto.setNGBIN612(map.get(key));}
                if (key.equals(613)){ngBinResultDto.setNGBIN613(map.get(key));}
                if (key.equals(614)){ngBinResultDto.setNGBIN614(map.get(key));}
                if (key.equals(615)){ngBinResultDto.setNGBIN615(map.get(key));}
                if (key.equals(616)){ngBinResultDto.setNGBIN616(map.get(key));}
                if (key.equals(617)){ngBinResultDto.setNGBIN617(map.get(key));}
                if (key.equals(618)){ngBinResultDto.setNGBIN618(map.get(key));}
                if (key.equals(619)){ngBinResultDto.setNGBIN619(map.get(key));}
                if (key.equals(620)){ngBinResultDto.setNGBIN620(map.get(key));}
                if (key.equals(621)){ngBinResultDto.setNGBIN621(map.get(key));}
                if (key.equals(622)){ngBinResultDto.setNGBIN622(map.get(key));}
                if (key.equals(623)){ngBinResultDto.setNGBIN623(map.get(key));}
                if (key.equals(624)){ngBinResultDto.setNGBIN624(map.get(key));}
                if (key.equals(625)){ngBinResultDto.setNGBIN625(map.get(key));}
                if (key.equals(626)){ngBinResultDto.setNGBIN626(map.get(key));}
                if (key.equals(627)){ngBinResultDto.setNGBIN627(map.get(key));}
                if (key.equals(628)){ngBinResultDto.setNGBIN628(map.get(key));}
                if (key.equals(629)){ngBinResultDto.setNGBIN629(map.get(key));}
                if (key.equals(630)){ngBinResultDto.setNGBIN630(map.get(key));}
                if (key.equals(631)){ngBinResultDto.setNGBIN631(map.get(key));}
                if (key.equals(632)){ngBinResultDto.setNGBIN632(map.get(key));}
                if (key.equals(633)){ngBinResultDto.setNGBIN633(map.get(key));}
                if (key.equals(634)){ngBinResultDto.setNGBIN634(map.get(key));}
                if (key.equals(635)){ngBinResultDto.setNGBIN635(map.get(key));}
                if (key.equals(636)){ngBinResultDto.setNGBIN636(map.get(key));}
                if (key.equals(637)){ngBinResultDto.setNGBIN637(map.get(key));}
                if (key.equals(638)){ngBinResultDto.setNGBIN638(map.get(key));}
                if (key.equals(639)){ngBinResultDto.setNGBIN639(map.get(key));}
                if (key.equals(640)){ngBinResultDto.setNGBIN640(map.get(key));}
                if (key.equals(641)){ngBinResultDto.setNGBIN641(map.get(key));}
                if (key.equals(642)){ngBinResultDto.setNGBIN642(map.get(key));}
                if (key.equals(643)){ngBinResultDto.setNGBIN643(map.get(key));}
                if (key.equals(644)){ngBinResultDto.setNGBIN644(map.get(key));}
                if (key.equals(645)){ngBinResultDto.setNGBIN645(map.get(key));}
                if (key.equals(646)){ngBinResultDto.setNGBIN646(map.get(key));}
                if (key.equals(647)){ngBinResultDto.setNGBIN647(map.get(key));}
                if (key.equals(648)){ngBinResultDto.setNGBIN648(map.get(key));}
                if (key.equals(649)){ngBinResultDto.setNGBIN649(map.get(key));}
                if (key.equals(650)){ngBinResultDto.setNGBIN650(map.get(key));}
                if (key.equals(651)){ngBinResultDto.setNGBIN651(map.get(key));}
                if (key.equals(652)){ngBinResultDto.setNGBIN652(map.get(key));}
                if (key.equals(653)){ngBinResultDto.setNGBIN653(map.get(key));}
                if (key.equals(654)){ngBinResultDto.setNGBIN654(map.get(key));}
                if (key.equals(655)){ngBinResultDto.setNGBIN655(map.get(key));}
                if (key.equals(656)){ngBinResultDto.setNGBIN656(map.get(key));}
                if (key.equals(657)){ngBinResultDto.setNGBIN657(map.get(key));}
                if (key.equals(658)){ngBinResultDto.setNGBIN658(map.get(key));}
                if (key.equals(659)){ngBinResultDto.setNGBIN659(map.get(key));}
                if (key.equals(660)){ngBinResultDto.setNGBIN660(map.get(key));}
                if (key.equals(661)){ngBinResultDto.setNGBIN661(map.get(key));}
                if (key.equals(662)){ngBinResultDto.setNGBIN662(map.get(key));}
                if (key.equals(663)){ngBinResultDto.setNGBIN663(map.get(key));}
                if (key.equals(664)){ngBinResultDto.setNGBIN664(map.get(key));}
                if (key.equals(665)){ngBinResultDto.setNGBIN665(map.get(key));}
                if (key.equals(666)){ngBinResultDto.setNGBIN666(map.get(key));}
                if (key.equals(667)){ngBinResultDto.setNGBIN667(map.get(key));}
                if (key.equals(668)){ngBinResultDto.setNGBIN668(map.get(key));}
                if (key.equals(669)){ngBinResultDto.setNGBIN669(map.get(key));}
                if (key.equals(670)){ngBinResultDto.setNGBIN670(map.get(key));}
                if (key.equals(671)){ngBinResultDto.setNGBIN671(map.get(key));}
                if (key.equals(672)){ngBinResultDto.setNGBIN672(map.get(key));}
                if (key.equals(673)){ngBinResultDto.setNGBIN673(map.get(key));}
                if (key.equals(674)){ngBinResultDto.setNGBIN674(map.get(key));}
                if (key.equals(675)){ngBinResultDto.setNGBIN675(map.get(key));}
                if (key.equals(676)){ngBinResultDto.setNGBIN676(map.get(key));}
                if (key.equals(677)){ngBinResultDto.setNGBIN677(map.get(key));}
                if (key.equals(678)){ngBinResultDto.setNGBIN678(map.get(key));}
                if (key.equals(679)){ngBinResultDto.setNGBIN679(map.get(key));}
                if (key.equals(680)){ngBinResultDto.setNGBIN680(map.get(key));}
                if (key.equals(681)){ngBinResultDto.setNGBIN681(map.get(key));}
                if (key.equals(682)){ngBinResultDto.setNGBIN682(map.get(key));}
                if (key.equals(683)){ngBinResultDto.setNGBIN683(map.get(key));}
                if (key.equals(684)){ngBinResultDto.setNGBIN684(map.get(key));}
                if (key.equals(685)){ngBinResultDto.setNGBIN685(map.get(key));}
                if (key.equals(686)){ngBinResultDto.setNGBIN686(map.get(key));}
                if (key.equals(687)){ngBinResultDto.setNGBIN687(map.get(key));}
                if (key.equals(688)){ngBinResultDto.setNGBIN688(map.get(key));}
                if (key.equals(689)){ngBinResultDto.setNGBIN689(map.get(key));}
                if (key.equals(690)){ngBinResultDto.setNGBIN690(map.get(key));}
                if (key.equals(691)){ngBinResultDto.setNGBIN691(map.get(key));}
                if (key.equals(692)){ngBinResultDto.setNGBIN692(map.get(key));}
                if (key.equals(693)){ngBinResultDto.setNGBIN693(map.get(key));}
                if (key.equals(694)){ngBinResultDto.setNGBIN694(map.get(key));}
                if (key.equals(695)){ngBinResultDto.setNGBIN695(map.get(key));}
                if (key.equals(696)){ngBinResultDto.setNGBIN696(map.get(key));}
                if (key.equals(697)){ngBinResultDto.setNGBIN697(map.get(key));}
                if (key.equals(698)){ngBinResultDto.setNGBIN698(map.get(key));}
                if (key.equals(699)){ngBinResultDto.setNGBIN699(map.get(key));}
                if (key.equals(700)){ngBinResultDto.setNGBIN700(map.get(key));}
                if (key.equals(701)){ngBinResultDto.setNGBIN701(map.get(key));}
                if (key.equals(702)){ngBinResultDto.setNGBIN702(map.get(key));}
                if (key.equals(703)){ngBinResultDto.setNGBIN703(map.get(key));}
                if (key.equals(704)){ngBinResultDto.setNGBIN704(map.get(key));}
                if (key.equals(705)){ngBinResultDto.setNGBIN705(map.get(key));}
                if (key.equals(706)){ngBinResultDto.setNGBIN706(map.get(key));}
                if (key.equals(707)){ngBinResultDto.setNGBIN707(map.get(key));}
                if (key.equals(708)){ngBinResultDto.setNGBIN708(map.get(key));}
                if (key.equals(709)){ngBinResultDto.setNGBIN709(map.get(key));}
                if (key.equals(710)){ngBinResultDto.setNGBIN710(map.get(key));}
                if (key.equals(711)){ngBinResultDto.setNGBIN711(map.get(key));}
                if (key.equals(712)){ngBinResultDto.setNGBIN712(map.get(key));}
                if (key.equals(713)){ngBinResultDto.setNGBIN713(map.get(key));}
                if (key.equals(714)){ngBinResultDto.setNGBIN714(map.get(key));}
                if (key.equals(715)){ngBinResultDto.setNGBIN715(map.get(key));}
                if (key.equals(716)){ngBinResultDto.setNGBIN716(map.get(key));}
                if (key.equals(717)){ngBinResultDto.setNGBIN717(map.get(key));}
                if (key.equals(718)){ngBinResultDto.setNGBIN718(map.get(key));}
                if (key.equals(719)){ngBinResultDto.setNGBIN719(map.get(key));}
                if (key.equals(720)){ngBinResultDto.setNGBIN720(map.get(key));}
                if (key.equals(721)){ngBinResultDto.setNGBIN721(map.get(key));}
                if (key.equals(722)){ngBinResultDto.setNGBIN722(map.get(key));}
                if (key.equals(723)){ngBinResultDto.setNGBIN723(map.get(key));}
                if (key.equals(724)){ngBinResultDto.setNGBIN724(map.get(key));}
                if (key.equals(725)){ngBinResultDto.setNGBIN725(map.get(key));}
                if (key.equals(726)){ngBinResultDto.setNGBIN726(map.get(key));}
                if (key.equals(727)){ngBinResultDto.setNGBIN727(map.get(key));}
                if (key.equals(728)){ngBinResultDto.setNGBIN728(map.get(key));}
                if (key.equals(729)){ngBinResultDto.setNGBIN729(map.get(key));}
                if (key.equals(730)){ngBinResultDto.setNGBIN730(map.get(key));}
                if (key.equals(731)){ngBinResultDto.setNGBIN731(map.get(key));}
                if (key.equals(732)){ngBinResultDto.setNGBIN732(map.get(key));}
                if (key.equals(733)){ngBinResultDto.setNGBIN733(map.get(key));}
                if (key.equals(734)){ngBinResultDto.setNGBIN734(map.get(key));}
                if (key.equals(735)){ngBinResultDto.setNGBIN735(map.get(key));}
                if (key.equals(736)){ngBinResultDto.setNGBIN736(map.get(key));}
                if (key.equals(737)){ngBinResultDto.setNGBIN737(map.get(key));}
                if (key.equals(738)){ngBinResultDto.setNGBIN738(map.get(key));}
                if (key.equals(739)){ngBinResultDto.setNGBIN739(map.get(key));}
                if (key.equals(740)){ngBinResultDto.setNGBIN740(map.get(key));}
                if (key.equals(741)){ngBinResultDto.setNGBIN741(map.get(key));}
                if (key.equals(742)){ngBinResultDto.setNGBIN742(map.get(key));}
                if (key.equals(743)){ngBinResultDto.setNGBIN743(map.get(key));}
                if (key.equals(744)){ngBinResultDto.setNGBIN744(map.get(key));}
                if (key.equals(745)){ngBinResultDto.setNGBIN745(map.get(key));}
                if (key.equals(746)){ngBinResultDto.setNGBIN746(map.get(key));}
                if (key.equals(747)){ngBinResultDto.setNGBIN747(map.get(key));}
                if (key.equals(748)){ngBinResultDto.setNGBIN748(map.get(key));}
                if (key.equals(749)){ngBinResultDto.setNGBIN749(map.get(key));}
                if (key.equals(750)){ngBinResultDto.setNGBIN750(map.get(key));}
                if (key.equals(751)){ngBinResultDto.setNGBIN751(map.get(key));}
                if (key.equals(752)){ngBinResultDto.setNGBIN752(map.get(key));}
                if (key.equals(753)){ngBinResultDto.setNGBIN753(map.get(key));}
                if (key.equals(754)){ngBinResultDto.setNGBIN754(map.get(key));}
                if (key.equals(755)){ngBinResultDto.setNGBIN755(map.get(key));}
                if (key.equals(756)){ngBinResultDto.setNGBIN756(map.get(key));}
                if (key.equals(757)){ngBinResultDto.setNGBIN757(map.get(key));}
                if (key.equals(758)){ngBinResultDto.setNGBIN758(map.get(key));}
                if (key.equals(759)){ngBinResultDto.setNGBIN759(map.get(key));}
                if (key.equals(760)){ngBinResultDto.setNGBIN760(map.get(key));}
                if (key.equals(761)){ngBinResultDto.setNGBIN761(map.get(key));}
                if (key.equals(762)){ngBinResultDto.setNGBIN762(map.get(key));}
                if (key.equals(763)){ngBinResultDto.setNGBIN763(map.get(key));}
                if (key.equals(764)){ngBinResultDto.setNGBIN764(map.get(key));}
                if (key.equals(765)){ngBinResultDto.setNGBIN765(map.get(key));}
                if (key.equals(766)){ngBinResultDto.setNGBIN766(map.get(key));}
                if (key.equals(767)){ngBinResultDto.setNGBIN767(map.get(key));}
                if (key.equals(768)){ngBinResultDto.setNGBIN768(map.get(key));}
                if (key.equals(769)){ngBinResultDto.setNGBIN769(map.get(key));}
                if (key.equals(770)){ngBinResultDto.setNGBIN770(map.get(key));}
                if (key.equals(771)){ngBinResultDto.setNGBIN771(map.get(key));}
                if (key.equals(772)){ngBinResultDto.setNGBIN772(map.get(key));}
                if (key.equals(773)){ngBinResultDto.setNGBIN773(map.get(key));}
                if (key.equals(774)){ngBinResultDto.setNGBIN774(map.get(key));}
                if (key.equals(775)){ngBinResultDto.setNGBIN775(map.get(key));}
                if (key.equals(776)){ngBinResultDto.setNGBIN776(map.get(key));}
                if (key.equals(777)){ngBinResultDto.setNGBIN777(map.get(key));}
                if (key.equals(778)){ngBinResultDto.setNGBIN778(map.get(key));}
                if (key.equals(779)){ngBinResultDto.setNGBIN779(map.get(key));}
                if (key.equals(780)){ngBinResultDto.setNGBIN780(map.get(key));}
                if (key.equals(781)){ngBinResultDto.setNGBIN781(map.get(key));}
                if (key.equals(782)){ngBinResultDto.setNGBIN782(map.get(key));}
                if (key.equals(783)){ngBinResultDto.setNGBIN783(map.get(key));}
                if (key.equals(784)){ngBinResultDto.setNGBIN784(map.get(key));}
                if (key.equals(785)){ngBinResultDto.setNGBIN785(map.get(key));}
                if (key.equals(786)){ngBinResultDto.setNGBIN786(map.get(key));}
                if (key.equals(787)){ngBinResultDto.setNGBIN787(map.get(key));}
                if (key.equals(788)){ngBinResultDto.setNGBIN788(map.get(key));}
                if (key.equals(789)){ngBinResultDto.setNGBIN789(map.get(key));}
                if (key.equals(790)){ngBinResultDto.setNGBIN790(map.get(key));}
                if (key.equals(791)){ngBinResultDto.setNGBIN791(map.get(key));}
                if (key.equals(792)){ngBinResultDto.setNGBIN792(map.get(key));}
                if (key.equals(793)){ngBinResultDto.setNGBIN793(map.get(key));}
                if (key.equals(794)){ngBinResultDto.setNGBIN794(map.get(key));}
                if (key.equals(795)){ngBinResultDto.setNGBIN795(map.get(key));}
                if (key.equals(796)){ngBinResultDto.setNGBIN796(map.get(key));}
                if (key.equals(797)){ngBinResultDto.setNGBIN797(map.get(key));}
                if (key.equals(798)){ngBinResultDto.setNGBIN798(map.get(key));}
                if (key.equals(799)){ngBinResultDto.setNGBIN799(map.get(key));}
                if (key.equals(800)){ngBinResultDto.setNGBIN800(map.get(key));}
                if (key.equals(801)){ngBinResultDto.setNGBIN801(map.get(key));}
                if (key.equals(802)){ngBinResultDto.setNGBIN802(map.get(key));}
                if (key.equals(803)){ngBinResultDto.setNGBIN803(map.get(key));}
                if (key.equals(804)){ngBinResultDto.setNGBIN804(map.get(key));}
                if (key.equals(805)){ngBinResultDto.setNGBIN805(map.get(key));}
                if (key.equals(806)){ngBinResultDto.setNGBIN806(map.get(key));}
                if (key.equals(807)){ngBinResultDto.setNGBIN807(map.get(key));}
                if (key.equals(808)){ngBinResultDto.setNGBIN808(map.get(key));}
                if (key.equals(809)){ngBinResultDto.setNGBIN809(map.get(key));}
                if (key.equals(810)){ngBinResultDto.setNGBIN810(map.get(key));}
                if (key.equals(811)){ngBinResultDto.setNGBIN811(map.get(key));}
                if (key.equals(812)){ngBinResultDto.setNGBIN812(map.get(key));}
                if (key.equals(813)){ngBinResultDto.setNGBIN813(map.get(key));}
                if (key.equals(814)){ngBinResultDto.setNGBIN814(map.get(key));}
                if (key.equals(815)){ngBinResultDto.setNGBIN815(map.get(key));}
                if (key.equals(816)){ngBinResultDto.setNGBIN816(map.get(key));}
                if (key.equals(817)){ngBinResultDto.setNGBIN817(map.get(key));}
                if (key.equals(818)){ngBinResultDto.setNGBIN818(map.get(key));}
                if (key.equals(819)){ngBinResultDto.setNGBIN819(map.get(key));}
                if (key.equals(820)){ngBinResultDto.setNGBIN820(map.get(key));}
                if (key.equals(821)){ngBinResultDto.setNGBIN821(map.get(key));}
                if (key.equals(822)){ngBinResultDto.setNGBIN822(map.get(key));}
                if (key.equals(823)){ngBinResultDto.setNGBIN823(map.get(key));}
                if (key.equals(824)){ngBinResultDto.setNGBIN824(map.get(key));}
                if (key.equals(825)){ngBinResultDto.setNGBIN825(map.get(key));}
                if (key.equals(826)){ngBinResultDto.setNGBIN826(map.get(key));}
                if (key.equals(827)){ngBinResultDto.setNGBIN827(map.get(key));}
                if (key.equals(828)){ngBinResultDto.setNGBIN828(map.get(key));}
                if (key.equals(829)){ngBinResultDto.setNGBIN829(map.get(key));}
                if (key.equals(830)){ngBinResultDto.setNGBIN830(map.get(key));}
                if (key.equals(831)){ngBinResultDto.setNGBIN831(map.get(key));}
                if (key.equals(832)){ngBinResultDto.setNGBIN832(map.get(key));}
                if (key.equals(833)){ngBinResultDto.setNGBIN833(map.get(key));}
                if (key.equals(834)){ngBinResultDto.setNGBIN834(map.get(key));}
                if (key.equals(835)){ngBinResultDto.setNGBIN835(map.get(key));}
                if (key.equals(836)){ngBinResultDto.setNGBIN836(map.get(key));}
                if (key.equals(837)){ngBinResultDto.setNGBIN837(map.get(key));}
                if (key.equals(838)){ngBinResultDto.setNGBIN838(map.get(key));}
                if (key.equals(839)){ngBinResultDto.setNGBIN839(map.get(key));}
                if (key.equals(840)){ngBinResultDto.setNGBIN840(map.get(key));}
                if (key.equals(841)){ngBinResultDto.setNGBIN841(map.get(key));}
                if (key.equals(842)){ngBinResultDto.setNGBIN842(map.get(key));}
                if (key.equals(843)){ngBinResultDto.setNGBIN843(map.get(key));}
                if (key.equals(844)){ngBinResultDto.setNGBIN844(map.get(key));}
                if (key.equals(845)){ngBinResultDto.setNGBIN845(map.get(key));}
                if (key.equals(846)){ngBinResultDto.setNGBIN846(map.get(key));}
                if (key.equals(847)){ngBinResultDto.setNGBIN847(map.get(key));}
                if (key.equals(848)){ngBinResultDto.setNGBIN848(map.get(key));}
                if (key.equals(849)){ngBinResultDto.setNGBIN849(map.get(key));}
                if (key.equals(850)){ngBinResultDto.setNGBIN850(map.get(key));}
                if (key.equals(851)){ngBinResultDto.setNGBIN851(map.get(key));}
                if (key.equals(852)){ngBinResultDto.setNGBIN852(map.get(key));}
                if (key.equals(853)){ngBinResultDto.setNGBIN853(map.get(key));}
                if (key.equals(854)){ngBinResultDto.setNGBIN854(map.get(key));}
                if (key.equals(855)){ngBinResultDto.setNGBIN855(map.get(key));}
                if (key.equals(856)){ngBinResultDto.setNGBIN856(map.get(key));}
                if (key.equals(857)){ngBinResultDto.setNGBIN857(map.get(key));}
                if (key.equals(858)){ngBinResultDto.setNGBIN858(map.get(key));}
                if (key.equals(859)){ngBinResultDto.setNGBIN859(map.get(key));}
                if (key.equals(860)){ngBinResultDto.setNGBIN860(map.get(key));}
                if (key.equals(861)){ngBinResultDto.setNGBIN861(map.get(key));}
                if (key.equals(862)){ngBinResultDto.setNGBIN862(map.get(key));}
                if (key.equals(863)){ngBinResultDto.setNGBIN863(map.get(key));}
                if (key.equals(864)){ngBinResultDto.setNGBIN864(map.get(key));}
                if (key.equals(865)){ngBinResultDto.setNGBIN865(map.get(key));}
                if (key.equals(866)){ngBinResultDto.setNGBIN866(map.get(key));}
                if (key.equals(867)){ngBinResultDto.setNGBIN867(map.get(key));}
                if (key.equals(868)){ngBinResultDto.setNGBIN868(map.get(key));}
                if (key.equals(869)){ngBinResultDto.setNGBIN869(map.get(key));}
                if (key.equals(870)){ngBinResultDto.setNGBIN870(map.get(key));}
                if (key.equals(871)){ngBinResultDto.setNGBIN871(map.get(key));}
                if (key.equals(872)){ngBinResultDto.setNGBIN872(map.get(key));}
                if (key.equals(873)){ngBinResultDto.setNGBIN873(map.get(key));}
                if (key.equals(874)){ngBinResultDto.setNGBIN874(map.get(key));}
                if (key.equals(875)){ngBinResultDto.setNGBIN875(map.get(key));}
                if (key.equals(876)){ngBinResultDto.setNGBIN876(map.get(key));}
                if (key.equals(877)){ngBinResultDto.setNGBIN877(map.get(key));}
                if (key.equals(878)){ngBinResultDto.setNGBIN878(map.get(key));}
                if (key.equals(879)){ngBinResultDto.setNGBIN879(map.get(key));}
                if (key.equals(880)){ngBinResultDto.setNGBIN880(map.get(key));}
                if (key.equals(881)){ngBinResultDto.setNGBIN881(map.get(key));}
                if (key.equals(882)){ngBinResultDto.setNGBIN882(map.get(key));}
                if (key.equals(883)){ngBinResultDto.setNGBIN883(map.get(key));}
                if (key.equals(884)){ngBinResultDto.setNGBIN884(map.get(key));}
                if (key.equals(885)){ngBinResultDto.setNGBIN885(map.get(key));}
                if (key.equals(886)){ngBinResultDto.setNGBIN886(map.get(key));}
                if (key.equals(887)){ngBinResultDto.setNGBIN887(map.get(key));}
                if (key.equals(888)){ngBinResultDto.setNGBIN888(map.get(key));}
                if (key.equals(889)){ngBinResultDto.setNGBIN889(map.get(key));}
                if (key.equals(890)){ngBinResultDto.setNGBIN890(map.get(key));}
                if (key.equals(891)){ngBinResultDto.setNGBIN891(map.get(key));}
                if (key.equals(892)){ngBinResultDto.setNGBIN892(map.get(key));}
                if (key.equals(893)){ngBinResultDto.setNGBIN893(map.get(key));}
                if (key.equals(894)){ngBinResultDto.setNGBIN894(map.get(key));}
                if (key.equals(895)){ngBinResultDto.setNGBIN895(map.get(key));}
                if (key.equals(896)){ngBinResultDto.setNGBIN896(map.get(key));}
                if (key.equals(897)){ngBinResultDto.setNGBIN897(map.get(key));}
                if (key.equals(898)){ngBinResultDto.setNGBIN898(map.get(key));}
                if (key.equals(899)){ngBinResultDto.setNGBIN899(map.get(key));}
                if (key.equals(900)){ngBinResultDto.setNGBIN900(map.get(key));}
                if (key.equals(901)){ngBinResultDto.setNGBIN901(map.get(key));}
                if (key.equals(902)){ngBinResultDto.setNGBIN902(map.get(key));}
                if (key.equals(903)){ngBinResultDto.setNGBIN903(map.get(key));}
                if (key.equals(904)){ngBinResultDto.setNGBIN904(map.get(key));}
                if (key.equals(905)){ngBinResultDto.setNGBIN905(map.get(key));}
                if (key.equals(906)){ngBinResultDto.setNGBIN906(map.get(key));}
                if (key.equals(907)){ngBinResultDto.setNGBIN907(map.get(key));}
                if (key.equals(908)){ngBinResultDto.setNGBIN908(map.get(key));}
                if (key.equals(909)){ngBinResultDto.setNGBIN909(map.get(key));}
                if (key.equals(910)){ngBinResultDto.setNGBIN910(map.get(key));}
                if (key.equals(911)){ngBinResultDto.setNGBIN911(map.get(key));}
                if (key.equals(912)){ngBinResultDto.setNGBIN912(map.get(key));}
                if (key.equals(913)){ngBinResultDto.setNGBIN913(map.get(key));}
                if (key.equals(914)){ngBinResultDto.setNGBIN914(map.get(key));}
                if (key.equals(915)){ngBinResultDto.setNGBIN915(map.get(key));}
                if (key.equals(916)){ngBinResultDto.setNGBIN916(map.get(key));}
                if (key.equals(917)){ngBinResultDto.setNGBIN917(map.get(key));}
                if (key.equals(918)){ngBinResultDto.setNGBIN918(map.get(key));}
                if (key.equals(919)){ngBinResultDto.setNGBIN919(map.get(key));}
                if (key.equals(920)){ngBinResultDto.setNGBIN920(map.get(key));}
                if (key.equals(921)){ngBinResultDto.setNGBIN921(map.get(key));}
                if (key.equals(922)){ngBinResultDto.setNGBIN922(map.get(key));}
                if (key.equals(923)){ngBinResultDto.setNGBIN923(map.get(key));}
                if (key.equals(924)){ngBinResultDto.setNGBIN924(map.get(key));}
                if (key.equals(925)){ngBinResultDto.setNGBIN925(map.get(key));}
                if (key.equals(926)){ngBinResultDto.setNGBIN926(map.get(key));}
                if (key.equals(927)){ngBinResultDto.setNGBIN927(map.get(key));}
                if (key.equals(928)){ngBinResultDto.setNGBIN928(map.get(key));}
                if (key.equals(929)){ngBinResultDto.setNGBIN929(map.get(key));}
                if (key.equals(930)){ngBinResultDto.setNGBIN930(map.get(key));}
                if (key.equals(931)){ngBinResultDto.setNGBIN931(map.get(key));}
                if (key.equals(932)){ngBinResultDto.setNGBIN932(map.get(key));}
                if (key.equals(933)){ngBinResultDto.setNGBIN933(map.get(key));}
                if (key.equals(934)){ngBinResultDto.setNGBIN934(map.get(key));}
                if (key.equals(935)){ngBinResultDto.setNGBIN935(map.get(key));}
                if (key.equals(936)){ngBinResultDto.setNGBIN936(map.get(key));}
                if (key.equals(937)){ngBinResultDto.setNGBIN937(map.get(key));}
                if (key.equals(938)){ngBinResultDto.setNGBIN938(map.get(key));}
                if (key.equals(939)){ngBinResultDto.setNGBIN939(map.get(key));}
                if (key.equals(940)){ngBinResultDto.setNGBIN940(map.get(key));}
                if (key.equals(941)){ngBinResultDto.setNGBIN941(map.get(key));}
                if (key.equals(942)){ngBinResultDto.setNGBIN942(map.get(key));}
                if (key.equals(943)){ngBinResultDto.setNGBIN943(map.get(key));}
                if (key.equals(944)){ngBinResultDto.setNGBIN944(map.get(key));}
                if (key.equals(945)){ngBinResultDto.setNGBIN945(map.get(key));}
                if (key.equals(946)){ngBinResultDto.setNGBIN946(map.get(key));}
                if (key.equals(947)){ngBinResultDto.setNGBIN947(map.get(key));}
                if (key.equals(948)){ngBinResultDto.setNGBIN948(map.get(key));}
                if (key.equals(949)){ngBinResultDto.setNGBIN949(map.get(key));}
                if (key.equals(950)){ngBinResultDto.setNGBIN950(map.get(key));}
                if (key.equals(951)){ngBinResultDto.setNGBIN951(map.get(key));}
                if (key.equals(952)){ngBinResultDto.setNGBIN952(map.get(key));}
                if (key.equals(953)){ngBinResultDto.setNGBIN953(map.get(key));}
                if (key.equals(954)){ngBinResultDto.setNGBIN954(map.get(key));}
                if (key.equals(955)){ngBinResultDto.setNGBIN955(map.get(key));}
                if (key.equals(956)){ngBinResultDto.setNGBIN956(map.get(key));}
                if (key.equals(957)){ngBinResultDto.setNGBIN957(map.get(key));}
                if (key.equals(958)){ngBinResultDto.setNGBIN958(map.get(key));}
                if (key.equals(959)){ngBinResultDto.setNGBIN959(map.get(key));}
                if (key.equals(960)){ngBinResultDto.setNGBIN960(map.get(key));}
                if (key.equals(961)){ngBinResultDto.setNGBIN961(map.get(key));}
                if (key.equals(962)){ngBinResultDto.setNGBIN962(map.get(key));}
                if (key.equals(963)){ngBinResultDto.setNGBIN963(map.get(key));}
                if (key.equals(964)){ngBinResultDto.setNGBIN964(map.get(key));}
                if (key.equals(965)){ngBinResultDto.setNGBIN965(map.get(key));}
                if (key.equals(966)){ngBinResultDto.setNGBIN966(map.get(key));}
                if (key.equals(967)){ngBinResultDto.setNGBIN967(map.get(key));}
                if (key.equals(968)){ngBinResultDto.setNGBIN968(map.get(key));}
                if (key.equals(969)){ngBinResultDto.setNGBIN969(map.get(key));}
                if (key.equals(970)){ngBinResultDto.setNGBIN970(map.get(key));}
                if (key.equals(971)){ngBinResultDto.setNGBIN971(map.get(key));}
                if (key.equals(972)){ngBinResultDto.setNGBIN972(map.get(key));}
                if (key.equals(973)){ngBinResultDto.setNGBIN973(map.get(key));}
                if (key.equals(974)){ngBinResultDto.setNGBIN974(map.get(key));}
                if (key.equals(975)){ngBinResultDto.setNGBIN975(map.get(key));}
                if (key.equals(976)){ngBinResultDto.setNGBIN976(map.get(key));}
                if (key.equals(977)){ngBinResultDto.setNGBIN977(map.get(key));}
                if (key.equals(978)){ngBinResultDto.setNGBIN978(map.get(key));}
                if (key.equals(979)){ngBinResultDto.setNGBIN979(map.get(key));}
                if (key.equals(980)){ngBinResultDto.setNGBIN980(map.get(key));}
                if (key.equals(981)){ngBinResultDto.setNGBIN981(map.get(key));}
                if (key.equals(982)){ngBinResultDto.setNGBIN982(map.get(key));}
                if (key.equals(983)){ngBinResultDto.setNGBIN983(map.get(key));}
                if (key.equals(984)){ngBinResultDto.setNGBIN984(map.get(key));}
                if (key.equals(985)){ngBinResultDto.setNGBIN985(map.get(key));}
                if (key.equals(986)){ngBinResultDto.setNGBIN986(map.get(key));}
                if (key.equals(987)){ngBinResultDto.setNGBIN987(map.get(key));}
                if (key.equals(988)){ngBinResultDto.setNGBIN988(map.get(key));}
                if (key.equals(989)){ngBinResultDto.setNGBIN989(map.get(key));}
                if (key.equals(990)){ngBinResultDto.setNGBIN990(map.get(key));}
                if (key.equals(991)){ngBinResultDto.setNGBIN991(map.get(key));}
                if (key.equals(992)){ngBinResultDto.setNGBIN992(map.get(key));}
                if (key.equals(993)){ngBinResultDto.setNGBIN993(map.get(key));}
                if (key.equals(994)){ngBinResultDto.setNGBIN994(map.get(key));}
                if (key.equals(995)){ngBinResultDto.setNGBIN995(map.get(key));}
                if (key.equals(996)){ngBinResultDto.setNGBIN996(map.get(key));}
                if (key.equals(997)){ngBinResultDto.setNGBIN997(map.get(key));}
                if (key.equals(998)){ngBinResultDto.setNGBIN998(map.get(key));}
                if (key.equals(999)){ngBinResultDto.setNGBIN999(map.get(key));}



            }
            ngBinResultDtoList.add(ngBinResultDto);
        }



//        stringList.add(allColumns);
        return ngBinResultDtoList;
    }

    public Map<String, Object> retrieveNgBinJson2(NgBinDto ngBinDto) {
        List<NgBinDto> ngBinDtoList = ngBinMapper.retireveNgBin(ngBinDto);

        logger.debug("NgBinService - retrieveNgBinJson2 : " + ngBinDtoList.get(0).getNgBin());

        return null;
    }
}
